// <auto-generated />
using System;
using ExpenseControlApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpenseControlApp.Migrations
{
    [DbContext(typeof(ExpenseDbContext))]
    partial class ExpenseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpenseControlApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#28a745",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 664, DateTimeKind.Utc).AddTicks(7180),
                            Description = "Monthly salary income",
                            Icon = "fas fa-money-bill-wave",
                            IsActive = true,
                            Name = "Salary",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#17a2b8",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(260),
                            Description = "Freelance work income",
                            Icon = "fas fa-laptop-code",
                            IsActive = true,
                            Name = "Freelance",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Color = "#6f42c1",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(270),
                            Description = "Investment returns",
                            Icon = "fas fa-chart-line",
                            IsActive = true,
                            Name = "Investment",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Color = "#fd7e14",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(270),
                            Description = "Food and restaurant expenses",
                            Icon = "fas fa-utensils",
                            IsActive = true,
                            Name = "Food & Dining",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Color = "#20c997",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(270),
                            Description = "Transport and fuel costs",
                            Icon = "fas fa-car",
                            IsActive = true,
                            Name = "Transportation",
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Color = "#dc3545",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(270),
                            Description = "Rent, mortgage, utilities",
                            Icon = "fas fa-home",
                            IsActive = true,
                            Name = "Housing",
                            Type = 2
                        },
                        new
                        {
                            Id = 7,
                            Color = "#e83e8c",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(270),
                            Description = "Medical and health expenses",
                            Icon = "fas fa-heartbeat",
                            IsActive = true,
                            Name = "Healthcare",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            Color = "#6c757d",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(270),
                            Description = "Movies, games, hobbies",
                            Icon = "fas fa-gamepad",
                            IsActive = true,
                            Name = "Entertainment",
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Color = "#ffc107",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(280),
                            Description = "Clothing and personal items",
                            Icon = "fas fa-shopping-bag",
                            IsActive = true,
                            Name = "Shopping",
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Color = "#6610f2",
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 665, DateTimeKind.Utc).AddTicks(280),
                            Description = "Courses, books, training",
                            Icon = "fas fa-graduation-cap",
                            IsActive = true,
                            Name = "Education",
                            Type = 2
                        });
                });

            modelBuilder.Entity("ExpenseControlApp.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("NextRecurringDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RecurringFrequency")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ExpenseControlApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 28, 21, 25, 44, 923, DateTimeKind.Utc).AddTicks(8020),
                            Email = "admin@expensecontrol.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$u.YKGtptfDsS4QYHZxdqP.jh.5ES/KqiOprYezcypdlp9nrO28U8e",
                            Role = 1
                        });
                });

            modelBuilder.Entity("ExpenseControlApp.Models.Transaction", b =>
                {
                    b.HasOne("ExpenseControlApp.Models.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ExpenseControlApp.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ExpenseControlApp.Models.Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ExpenseControlApp.Models.User", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
